name: Container Build

on:
  push:
  workflow_dispatch:

jobs:
  ContinuousDelivery:
    runs-on: [ubuntu-latest]
    name: Continuous delivery (Create and push shippable container image)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.actor}}/${{ github.event.repository.name }}:latest
